# -*- coding: utf-8 -*-
"""
Mento.AI Semantic Matcher & Topic Detection Engine
Uses SBERT (Sentence-Transformers) + FAISS when available,
or fast TF-IDF N-gram Cosine Similarity for lightweight serverless environments.
Matches syllabus topics to study material chunks, identifies 'Other Topics'
present in the study material that were not part of the syllabus, and guarantees
zero content loss by retaining all remaining source pages and sections.
"""

import re
import logging
import numpy as np
from typing import List, Dict, Any, Optional, Set, Tuple

from backend.core.heading_detector import is_valid_academic_heading, clean_heading_title

logger = logging.getLogger("matcher")

_MODEL_INSTANCE = None
SBERT_AVAILABLE = False
FAISS_AVAILABLE = False

try:
    import faiss
    FAISS_AVAILABLE = True
except ImportError:
    FAISS_AVAILABLE = False

try:
    import sentence_transformers
    SBERT_AVAILABLE = True
except ImportError:
    SBERT_AVAILABLE = False

def get_embedding_model():
    """Lazy load SBERT model for embedding generation if available."""
    global _MODEL_INSTANCE
    if not SBERT_AVAILABLE or not FAISS_AVAILABLE:
        return None
        
    if _MODEL_INSTANCE is None:
        try:
            from sentence_transformers import SentenceTransformer
            logger.info("Loading SBERT model (all-MiniLM-L6-v2)...")
            _MODEL_INSTANCE = SentenceTransformer('all-MiniLM-L6-v2')
            logger.info("SBERT model loaded successfully.")
        except Exception as e:
            logger.warning(f"Could not load SentenceTransformer: {e}. Falling back to TF-IDF matching.")
            return None
    return _MODEL_INSTANCE

def extract_candidate_headings_from_chunks(chunks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Extracts candidate section headers and topic titles from study material chunks.
    Only allows meaningful academic headings (section titles, chapter titles, numbered topics).
    Strictly filters out stopwords, random OCR fragments, narrative sentences, and metadata.
    """
    candidates = []
    seen_titles = set()
    
    for chunk in chunks:
        # 1. Direct section heading if generated by structure-aware segmenter
        if chunk.get("is_structured_section") and chunk.get("heading"):
            heading = chunk["heading"].strip()
            hierarchy = chunk.get("hierarchy_number", "").strip()
            if is_valid_academic_heading(heading) and heading.lower() not in seen_titles:
                seen_titles.add(heading.lower())
                candidates.append({
                    "title": heading,
                    "hierarchy_number": hierarchy,
                    "chunk_id": chunk["chunk_id"],
                    "chunk": chunk
                })
                
        # 2. Check lines inside the chunk text for any sub-headings
        lines = chunk.get("text", "").splitlines()
        for line in lines:
            line_str = line.strip()
            if not is_valid_academic_heading(line_str):
                continue
                
            clean_title, hierarchy_num = clean_heading_title(line_str)
            norm_key = clean_title.lower().strip()
            if norm_key in seen_titles:
                continue
            if not is_valid_academic_heading(clean_title) and not hierarchy_num:
                continue
                
            seen_titles.add(norm_key)
            candidates.append({
                "title": clean_title,
                "hierarchy_number": hierarchy_num,
                "chunk_id": chunk["chunk_id"],
                "chunk": chunk
            })
            
    return candidates

def _extract_other_topics(
    chunks: List[Dict[str, Any]],
    matched_chunk_ids: Set[str],
    topics: List[Dict[str, Any]],
    model=None
) -> Tuple[List[Dict[str, Any]], Set[str]]:
    """
    Identifies and structures non-syllabus topics found in the study material.
    STRICT RULE: Only verified academic headings are allowed as other topics.
    Returns: (other_topics, updated_covered_chunk_ids)
    """
    candidate_headings = extract_candidate_headings_from_chunks(chunks)
    other_topics = []
    other_topic_idx = 1
    covered_chunk_ids = set(matched_chunk_ids)
    
    if candidate_headings and topics:
        syllabus_titles = [t["full_context"].lower() for t in topics]
        
        from sklearn.feature_extraction.text import TfidfVectorizer
        from sklearn.metrics.pairwise import cosine_similarity
        
        cand_titles = [c["title"].lower() for c in candidate_headings]
        all_txts = cand_titles + syllabus_titles
        
        try:
            vec = TfidfVectorizer(ngram_range=(1, 2), stop_words='english')
            mat = vec.fit_transform(all_txts)
            c_mat = mat[:len(cand_titles)]
            s_mat = mat[len(cand_titles):]
            sims = cosine_similarity(c_mat, s_mat)
        except Exception:
            sims = np.zeros((len(cand_titles), len(syllabus_titles)))
            
        for i, cand in enumerate(candidate_headings):
            max_syl_sim = float(np.max(sims[i])) if len(syllabus_titles) > 0 else 0.0
            
            # If this heading is NOT strongly similar to any syllabus topic (< 0.40), it is an Other Topic!
            if max_syl_sim < 0.40:
                cand_chunk = cand["chunk"]
                topic_chunks = [cand_chunk]
                covered_chunk_ids.add(cand_chunk["chunk_id"])
                
                # Find other chunks belonging to this same heading
                cand_heading_lower = cand["title"].lower()
                for c in chunks:
                    if c["chunk_id"] not in covered_chunk_ids:
                        if c.get("heading", "").lower() == cand_heading_lower:
                            topic_chunks.append(c)
                            covered_chunk_ids.add(c["chunk_id"])
                                
                matches_list = []
                for tc in topic_chunks:
                    matches_list.append({
                        "chunk_id": tc["chunk_id"],
                        "text": tc.get("text", ""),
                        "page_number": tc.get("page_number", 1),
                        "type": tc.get("type", "digital"),
                        "source": tc.get("source", "Study Material"),
                        "images": tc.get("images", []),
                        "tables": tc.get("tables", []),
                        "score": 1.0,
                        "similarity_score": 1.0,
                        "confidence_pct": 100.0
                    })
                    
                other_topics.append({
                    "topic_id": f"other_topic_{other_topic_idx}",
                    "title": cand["title"],
                    "unit": "Other Topics Found in Study Material",
                    "section": "",
                    "hierarchy_number": cand["hierarchy_number"],
                    "full_context": f"Other Topics > {cand['title']}",
                    "is_other_topic": True,
                    "similarity_score": 1.0,
                    "confidence_pct": 100.0,
                    "source_chunks": [tc["chunk_id"] for tc in topic_chunks],
                    "matches": matches_list
                })
                other_topic_idx += 1
                
    return other_topics, covered_chunk_ids

def _group_remaining_unmatched_chunks(
    chunks: List[Dict[str, Any]],
    covered_chunk_ids: Set[str]
) -> List[Dict[str, Any]]:
    """
    CRITICAL ZERO DATA LOSS HANDLER:
    Gathers all remaining chunks across all pages that were not claimed by syllabus topics
    or explicit other topics. Groups them by source document and page ranges into
    additional topics so 100% of pages and content are preserved.
    """
    remaining_chunks = [c for c in chunks if c["chunk_id"] not in covered_chunk_ids]
    if not remaining_chunks:
        return []

    logger.info(f"Preserving {len(remaining_chunks)} additional source chunks to guarantee zero data loss.")
    
    # Group remaining chunks by (source, page_number)
    grouped_by_page: Dict[Tuple[str, int], List[Dict[str, Any]]] = {}
    for c in remaining_chunks:
        key = (c.get("source", "Study Material"), c.get("page_number", 1))
        if key not in grouped_by_page:
            grouped_by_page[key] = []
        grouped_by_page[key].append(c)

    additional_topics = []
    add_idx = 1
    
    # Sort by source, then page number
    for (src, p_num), p_chunks in sorted(grouped_by_page.items(), key=lambda item: (item[0][0], item[0][1])):
        matches_list = []
        for c in p_chunks:
            matches_list.append({
                "chunk_id": c["chunk_id"],
                "text": c.get("text", ""),
                "page_number": c.get("page_number", p_num),
                "type": c.get("type", "digital"),
                "source": src,
                "images": c.get("images", []),
                "tables": c.get("tables", []),
                "score": 0.80,
                "similarity_score": 0.80,
                "confidence_pct": 80.0
            })
            
        topic_title = f"Additional Notes — Page {p_num} ({src})"
        additional_topics.append({
            "topic_id": f"add_topic_{add_idx}",
            "title": topic_title,
            "unit": "Additional Source Material & Notes",
            "section": "",
            "hierarchy_number": str(p_num),
            "full_context": f"Additional Notes > {topic_title}",
            "is_other_topic": True,
            "similarity_score": 0.80,
            "confidence_pct": 80.0,
            "source_chunks": [c["chunk_id"] for c in p_chunks],
            "matches": matches_list
        })
        add_idx += 1

    return additional_topics

def _match_with_tfidf(
    topics: List[Dict[str, Any]],
    chunks: List[Dict[str, Any]],
    similarity_threshold: float,
    top_k: int
) -> Dict[str, Any]:
    """
    High-speed, lightweight TF-IDF n-gram cosine matching for serverless deployment.
    """
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.metrics.pairwise import cosine_similarity

    chunk_texts = [
        f"{c.get('heading', '')} {c.get('text', '')}".strip() if c.get('heading') else c.get("text", "")
        for c in chunks
    ]
    topic_texts = [t["full_context"] for t in topics]

    vectorizer = TfidfVectorizer(
        ngram_range=(1, 3),
        sublinear_tf=True,
        token_pattern=r'(?u)\b[\w-]+\b'
    )
    
    all_texts = chunk_texts + topic_texts
    tfidf_matrix = vectorizer.fit_transform(all_texts)
    
    num_chunks = len(chunks)
    chunk_vecs = tfidf_matrix[:num_chunks]
    topic_vecs = tfidf_matrix[num_chunks:]

    sim_matrix = cosine_similarity(topic_vecs, chunk_vecs)
    
    syllabus_results = []
    matched_chunk_ids = set()

    for i, topic in enumerate(topics):
        topic_matches = []
        topic_sims = sim_matrix[i]
        
        ranked_indices = np.argsort(-topic_sims)
        effective_threshold = min(similarity_threshold, 0.15)
        
        for rank in range(min(top_k, len(ranked_indices))):
            idx = int(ranked_indices[rank])
            score = float(topic_sims[idx])
            
            if score >= effective_threshold or (rank == 0 and score > 0.04):
                matched_chunk = chunks[idx]
                matched_chunk_ids.add(matched_chunk["chunk_id"])
                display_score = min(round(score * 1.5, 4), 0.99)
                topic_matches.append({
                    "chunk_id": matched_chunk["chunk_id"],
                    "text": matched_chunk.get("text", ""),
                    "page_number": matched_chunk.get("page_number", 1),
                    "type": matched_chunk.get("type", "digital"),
                    "source": matched_chunk.get("source", "Study Material"),
                    "images": matched_chunk.get("images", []),
                    "tables": matched_chunk.get("tables", []),
                    "score": display_score,
                    "similarity_score": display_score,
                    "confidence_pct": round(display_score * 100, 1)
                })

        topic_matches.sort(key=lambda x: x["score"], reverse=True)
        syllabus_results.append({
            "topic_id": topic["topic_id"],
            "title": topic["title"],
            "unit": topic["unit"],
            "section": topic.get("section", ""),
            "hierarchy_number": topic.get("hierarchy_number", ""),
            "full_context": topic["full_context"],
            "is_other_topic": False,
            "similarity_score": topic_matches[0]["similarity_score"] if topic_matches else 0.0,
            "confidence_pct": topic_matches[0]["confidence_pct"] if topic_matches else 0.0,
            "source_chunks": [m["chunk_id"] for m in topic_matches],
            "matches": topic_matches
        })

    # Detect Other Topics from study material
    other_topics, covered_chunk_ids = _extract_other_topics(chunks, matched_chunk_ids, topics)
    
    # Retain all remaining unmatched chunks to guarantee ZERO data loss
    additional_notes_topics = _group_remaining_unmatched_chunks(chunks, covered_chunk_ids)
    all_other_topics = other_topics + additional_notes_topics
    
    combined_topics = syllabus_results + all_other_topics
    chunks_map = {c["chunk_id"]: c for c in chunks}
    coverage = compute_coverage_audit(syllabus_results)
    
    return {
        "syllabus_topics": syllabus_results,
        "other_topics": all_other_topics,
        "topics": combined_topics,
        "chunks": chunks_map,
        "coverage": coverage
    }

def match_syllabus_to_document(
    topics: List[Dict[str, Any]],
    chunks: List[Dict[str, Any]],
    similarity_threshold: float = 0.35,
    top_k: int = 5
) -> Dict[str, Any]:
    """
    Perform semantic search to match syllabus topics to document chunks.
    Uses SBERT + FAISS if available, otherwise fast TF-IDF.
    Returns structured syllabus_topics, other_topics, chunks_map, and coverage report.
    """
    if not topics or not chunks:
        logger.warning("Empty topics or chunks provided for matching.")
        return {
            "syllabus_topics": [],
            "other_topics": [],
            "topics": [],
            "chunks": {},
            "coverage": compute_coverage_audit([])
        }
        
    model = get_embedding_model()
    if model is None or not FAISS_AVAILABLE:
        logger.info("Using lightweight TF-IDF semantic matcher for serverless execution.")
        return _match_with_tfidf(topics, chunks, similarity_threshold, top_k)
        
    import faiss
    
    # 1. Embed study material chunks
    logger.info(f"Embedding {len(chunks)} document chunks with SBERT...")
    chunk_texts = [
        f"{chunk.get('heading', '')} {chunk.get('text', '')}".strip() if chunk.get('heading') else chunk.get("text", "")
        for chunk in chunks
    ]
    chunk_embeddings = model.encode(chunk_texts, show_progress_bar=False, convert_to_numpy=True)
    faiss.normalize_L2(chunk_embeddings)
    
    # 2. Build FAISS index
    dimension = chunk_embeddings.shape[1]
    index = faiss.IndexFlatIP(dimension)
    index.add(chunk_embeddings)
    
    # 3. Embed syllabus topics
    logger.info(f"Embedding {len(topics)} syllabus topics...")
    topic_texts = [topic["full_context"] for topic in topics]
    topic_embeddings = model.encode(topic_texts, show_progress_bar=False, convert_to_numpy=True)
    faiss.normalize_L2(topic_embeddings)
    
    # 4. Search index
    scores, indices = index.search(topic_embeddings, k=min(top_k, len(chunks)))
    
    # 5. Compile results
    syllabus_results = []
    matched_chunk_ids = set()
    
    for i, topic in enumerate(topics):
        topic_matches = []
        for rank in range(min(top_k, len(chunks))):
            score = float(scores[i][rank])
            idx = int(indices[i][rank])
            
            if idx == -1:
                continue
                
            if score >= similarity_threshold or (rank == 0 and score >= 0.22):
                matched_chunk = chunks[idx]
                matched_chunk_ids.add(matched_chunk["chunk_id"])
                display_score = round(score, 4)
                topic_matches.append({
                    "chunk_id": matched_chunk["chunk_id"],
                    "text": matched_chunk.get("text", ""),
                    "page_number": matched_chunk.get("page_number", 1),
                    "type": matched_chunk.get("type", "digital"),
                    "source": matched_chunk.get("source", "Study Material"),
                    "images": matched_chunk.get("images", []),
                    "tables": matched_chunk.get("tables", []),
                    "score": display_score,
                    "similarity_score": display_score,
                    "confidence_pct": round(display_score * 100, 1)
                })
        
        topic_matches.sort(key=lambda x: x["score"], reverse=True)
        syllabus_results.append({
            "topic_id": topic["topic_id"],
            "title": topic["title"],
            "unit": topic["unit"],
            "section": topic.get("section", ""),
            "hierarchy_number": topic.get("hierarchy_number", ""),
            "full_context": topic["full_context"],
            "is_other_topic": False,
            "similarity_score": topic_matches[0]["similarity_score"] if topic_matches else 0.0,
            "confidence_pct": topic_matches[0]["confidence_pct"] if topic_matches else 0.0,
            "source_chunks": [m["chunk_id"] for m in topic_matches],
            "matches": topic_matches
        })
        
    # 6. Detect Other Topics from study material
    other_topics, covered_chunk_ids = _extract_other_topics(chunks, matched_chunk_ids, topics, model=model)
    
    # 7. Retain all remaining unmatched chunks to guarantee ZERO data loss
    additional_notes_topics = _group_remaining_unmatched_chunks(chunks, covered_chunk_ids)
    all_other_topics = other_topics + additional_notes_topics
    
    combined_topics = syllabus_results + all_other_topics
    chunks_map = {c["chunk_id"]: c for c in chunks}
    coverage = compute_coverage_audit(syllabus_results)
    
    logger.info(f"Syllabus matching complete: {len(syllabus_results)} syllabus topics, {len(all_other_topics)} other/additional topics.")
    
    return {
        "syllabus_topics": syllabus_results,
        "other_topics": all_other_topics,
        "topics": combined_topics,
        "chunks": chunks_map,
        "coverage": coverage
    }

def compute_coverage_audit(matched_results: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Computes coverage metrics comparing syllabus topics against study material matches.
    """
    syl_topics = [t for t in matched_results if not t.get("is_other_topic", False)]
    if not syl_topics:
        syl_topics = matched_results
        
    total_topics = len(syl_topics)
    covered_topics = []
    missing_topics = []
    total_excerpts = 0
    
    for item in syl_topics:
        matches = item.get("matches", [])
        match_count = len(matches)
        total_excerpts += match_count
        
        topic_info = {
            "topic_id": item.get("topic_id"),
            "title": item.get("title"),
            "unit": item.get("unit"),
            "hierarchy_number": item.get("hierarchy_number"),
            "match_count": match_count
        }
        
        if match_count > 0:
            covered_topics.append(topic_info)
        else:
            missing_topics.append(topic_info)
            
    matched_count = len(covered_topics)
    missing_count = len(missing_topics)
    coverage_pct = round((matched_count / total_topics * 100), 1) if total_topics > 0 else 0.0
    
    return {
        "total_topics": total_topics,
        "matched_topics_count": matched_count,
        "missing_topics_count": missing_count,
        "coverage_percentage": coverage_pct,
        "total_excerpts": total_excerpts,
        "covered_topics": covered_topics,
        "missing_topics": missing_topics
    }
